name: Build and Upload Wheels

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Build wheel
        run: python setup.py bdist_wheel

      - name: Upload wheel
        uses: actions/upload-artifact@v2
        with:
          name: my-wheels
          path: dist/*.whl
